from ._version import __version__
from .callables import (
    CallableReportEntry,
    callable_report_entries,
    render_callable_report,
    structured_callable_report,
)
from .extraction import (
    CodeMap,
    CodeMapSerializationError,
    ExtractionCache,
    SourceChangedDuringExtractionError,
    SourceManifest,
    SourceManifestEntry,
    SourceRoots,
    deserialize_code_map,
    discover_sources,
    extract_code,
    serialize_code_map,
)
from .extractors.loader import (
    UnsupportedLanguageError,
    normalize_source_id,
    supported_languages,
)
from .exports import UnusedExport, find_unused_exports
from .graph import DependencyGraph, Edge, Node, build_dependency_graph
from .metadata import (
    EXTRACTION_SCHEMA_VERSION,
    PUBLIC_API_STABILITY,
    ExtractorRuntimeError,
    LanguageInfo,
    MissingRuntimeError,
    RuntimeInfo,
    extraction_implementation_stamp,
    language,
    languages,
    require_runtime,
    runtime_diagnostics,
)
from .shape import (
    ShapeConfig,
    ShapeConfigError,
    ShapeConfigIssue,
    ShapePolicyEvaluator,
    ShapeViolation,
    evaluate_shape,
    validate_shape_config,
)


__all__ = [
    "CodeMap",
    "CodeMapSerializationError",
    "CallableReportEntry",
    "DependencyGraph",
    "Edge",
    "EXTRACTION_SCHEMA_VERSION",
    "ExtractionCache",
    "ExtractorRuntimeError",
    "LanguageInfo",
    "MissingRuntimeError",
    "Node",
    "PUBLIC_API_STABILITY",
    "RuntimeInfo",
    "ShapeConfig",
    "ShapeConfigError",
    "ShapeConfigIssue",
    "ShapePolicyEvaluator",
    "ShapeViolation",
    "SourceChangedDuringExtractionError",
    "SourceManifest",
    "SourceManifestEntry",
    "SourceRoots",
    "UnsupportedLanguageError",
    "UnusedExport",
    "__version__",
    "build_dependency_graph",
    "callable_report_entries",
    "deserialize_code_map",
    "discover_sources",
    "evaluate_shape",
    "extraction_implementation_stamp",
    "extract_code",
    "find_unused_exports",
    "language",
    "languages",
    "normalize_source_id",
    "require_runtime",
    "render_callable_report",
    "runtime_diagnostics",
    "serialize_code_map",
    "structured_callable_report",
    "supported_languages",
    "validate_shape_config",
]
